language: node_js
node_js:
  - "8"
before_install:
 - openssl aes-256-cbc -K $encrypted_a02a81ac195c_key -iv $encrypted_a02a81ac195c_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install: true
 - npm install
script:
 - chmod 600 deploy_rsa
 - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
 - ssh -vvv -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
